version: '3.8'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
      - shared-data:/shared-data
    networks:
      - app-network  # Place le service sur le réseau Docker partagé
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2  # Change-le plus tard pour ta vraie base
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
    networks:
      - app-network
    depends_on:
      - springboot-app

  init-metabase:
    build: ./init-metabase
    depends_on:
      - metabase
    networks:
      - app-network
    environment:
      MB_URL: http://metabase:3000
      MB_USER: admin@admin.com
      MB_PASSWORD: admin123
      MONGO_URI: "mongodb+srv://batistegros:23aSCw2cIGDpvEmO@cluster0.agiit.mongodb.net"
      MONGO_DB: "sample_mflix"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - postgres


networks:
  app-network:
    driver: bridge


volumes:
  shared-data: # Définition du volume partagé
  pgdata: #volume postgre