# application-docker.yml

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/db
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ou create-drop si tu veux recréer à chaque lancement
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
